# Generated by Django 5.1.1 on 2024-09-30 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_remove_team_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=500)),
                ('date', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_end', models.BooleanField(default=False)),
                ('invitation_num', models.CharField(blank=True, max_length=10, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='teams.team')),
            ],
        ),
    ]
