# Generated by Django 5.1.1 on 2024-09-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='comment',
        ),
    ]
