# Generated by Django 5.1.1 on 2024-09-30 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_remove_team_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('character_image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='teams.userteamprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
